### ISSUE TITLE
Travis for master and PRs?

### ISSUE THREAD

**Issue by gliptak** [f5devcentral/terraform-provider-f5#3]
Please enable this project in this Travis console. Thanks

**Comment by scshitole** [comment]
I am using OS X and Travis CI says Go builds are not available on the OS X environment.
https://docs.travis-ci.com/user/languages/go/
Any other option you can suggest ?

**Comment by gliptak** [comment]
The ```Makefile``` already has [Gox](https://github.com/mitchellh/gox) which cross-compiles (including OSX), so running under ```OSX``` is not required.

After ```go build``` successful (as suggested in https://github.com/f5devcentral/terraform-provider-f5/issues/1), I can update ```.travis.yml``` and ```Makefile```

[CircleCI](https://circleci.com/) also offers OSX images (I do not have Golang specifics)

**Comment by scshitole** [comment]
I tried triggering build with Travis CI build fails giving error The command "go get github.com/hashicorp/terraform" failed and exited with 2 during .

**Comment by gliptak** [comment]
Current version of ```Terraform``` requires ```Go 1.9+```

I submitted https://github.com/f5devcentral/terraform-provider-f5/pull/6

**Comment by scshitole** [comment]
I think its failing in this section of make file ?
get-deps:
	@go get -t -v ./...
	@if [ ! -d "$(TF_DIR)" ]; then \
		go get github.com/hashicorp/terraform; \
		if [ ! -d "$(TF_DIR)" ]; then \
			echo "ERROR: terraform could not be found. $(TF_DIR)"; \
			exit 1; \
		fi \
	fi
	@if [ ! -d "$(BIGIP_BIN_PATH)" ]; then \
		mkdir "$(BIGIP_BIN_PATH)"; \
	fi

fmt:
	@gofmt -l -w . bigip/

**Comment by gliptak** [comment]
https://github.com/f5devcentral/terraform-provider-f5/pull/7

**Comment by gliptak** [comment]
Reason for the current build failure is that the vendored version

https://github.com/f5devcentral/terraform-provider-f5/tree/master/vendor/github.com/scottdware/go-bigip

used for ```go test```

doesn't much with ```HEAD```

https://github.com/scottdware/go-bigip

used for ```make bin```

**Comment by gliptak** [comment]
Build is green, and PRs are enabled. Thanks
